/**
 * Run `surface init` over real public repositories and write a table of what
 * happened. This is the "works on real repos" claim, measured: how many
 * capabilities, how much of it is inference, which health findings, how long,
 * and - most usefully - whether it crashed.
 *
 * Clones are shallow and pinned; nothing is executed inside the cloned
 * repositories (init never runs project commands). Needs git and network;
 * runs in the weekly workflow and on demand.
 *
 *   node bench/corpus-run.mjs                 all repositories
 *   node bench/corpus-run.mjs --only gin-gonic/gin
 *   node bench/corpus-run.mjs --keep          leave the clones in the temp dir
 */

import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL("./", import.meta.url));
const CLI = fileURLToPath(new URL("../packages/cli/dist/index.js", import.meta.url));
const { values } = parseArgs({ options: { only: { type: "string" }, keep: { type: "boolean", default: false } } });

const corpus = JSON.parse(readFileSync(join(HERE, "corpus.json"), "utf8")).repositories.filter(
  (r) => !values.only || r.name === values.only
);
const toolCommit = (() => {
  try {
    return execFileSync("git", ["rev-parse", "--short", "HEAD"], { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
})();

const rows = [];
for (const repo of corpus) {
  const dir = mkdtempSync(join(tmpdir(), "surface-corpus-"));
  const row = { ...repo, status: "ok" };
  const started = Date.now();
  try {
    const clone = spawnSync("git", ["clone", "--quiet", "--depth", "1", "--branch", repo.ref, repo.url, dir], { encoding: "utf8" });
    if (clone.status !== 0) throw new Error(`clone failed: ${clone.stderr.trim().split("\n").pop()}`);

    const init = spawnSync(process.execPath, [CLI, "init", "--root", dir, "--json"], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
    row.initMs = Date.now() - started;
    if (init.status !== 0) {
      row.status = "crashed";
      row.error = (init.stderr || init.stdout).trim().split("\n").slice(-3).join(" | ");
    } else {
      const surface = JSON.parse(readFileSync(join(dir, ".project", "surface.json"), "utf8"));
      const tiers = {};
      for (const c of surface.capabilities) tiers[c.provenance.tier] = (tiers[c.provenance.tier] ?? 0) + 1;
      row.stacks = surface.project.stacks.map((s) => s.id + (s.toolchainAvailable ? "" : "*")).join(", ");
      row.packages = surface.project.packages.length;
      row.commands = surface.commands.length;
      row.capabilities = surface.capabilities.length;
      row.tiers = tiers;
      row.linked = surface.capabilities.filter((c) => c.evidence.length > 0).length;
      row.constraints = surface.constraints.length;
      row.environment = surface.environment.length;
      row.health = {};
      for (const h of surface.health) row.health[h.severity] = (row.health[h.severity] ?? 0) + 1;
      row.warnings = [...new Set(surface.health.filter((h) => h.severity !== "info").map((h) => h.code))].sort().join(", ");
    }
  } catch (e) {
    row.status = "failed";
    row.error = String(e.message ?? e);
  } finally {
    if (!values.keep) rmSync(dir, { recursive: true, force: true });
  }
  console.log(`${row.status.padEnd(8)} ${repo.name}@${repo.ref}  ${row.capabilities ?? "-"} capabilities  ${row.initMs ?? "-"} ms${row.error ? `  ${row.error}` : ""}`);
  rows.push(row);
}

const date = new Date().toISOString().slice(0, 10);
const lines = [
  "# Corpus run",
  "",
  `Generated by \`node bench/corpus-run.mjs\` on ${date} with project-surface at \`${toolCommit}\`. Do not edit by hand.`,
  "",
  "`surface init` over pinned public repositories. Nothing inside a repository is executed, so every capability is `derived` or `inferred` and evidence is `unknown` - this measures extraction, not verification. A stack marked `*` had no toolchain on the runner.",
  "",
  "| Repository | Ref | Stacks | Pkgs | Cmds | Capabilities | derived / inferred | With evidence | Constraints | Env | Health (error / warn / info) | Warnings | Time |",
  "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
];
for (const r of rows) {
  if (r.status !== "ok") {
    lines.push(`| ${r.name} | ${r.ref} | **${r.status}** | | | | | | | | | ${r.error ?? ""} | ${r.initMs ?? "-"} ms |`);
    continue;
  }
  lines.push(
    `| ${r.name} | ${r.ref} | ${r.stacks} | ${r.packages} | ${r.commands} | ${r.capabilities} | ${r.tiers.derived ?? 0} / ${r.tiers.inferred ?? 0} | ${r.linked} | ${r.constraints} | ${r.environment} | ${r.health.error ?? 0} / ${r.health.warn ?? 0} / ${r.health.info ?? 0} | ${r.warnings} | ${(r.initMs / 1000).toFixed(1)} s |`
  );
}
lines.push("");
const crashed = rows.filter((r) => r.status !== "ok");
lines.push(crashed.length === 0 ? `No crashes across ${rows.length} repositories.` : `**${crashed.length} of ${rows.length} repositories did not scan cleanly.** Each is a bug; open an issue with the row.`);
lines.push("");
writeFileSync(join(HERE, "corpus", "RESULTS.md"), `${lines.join("\n")}\n`);
console.log("wrote bench/corpus/RESULTS.md");
