/**
 * Grade the recorded answers and write RESULTS.md. Offline, deterministic.
 *
 * Reads bench/recorded/, never the network. Re-derives each prompt from the
 * fixtures and compares its hash with the one stored at recording time, so a
 * result table can never quietly describe a benchmark that no longer exists:
 * a drifted prompt is reported in the table, per question.
 *
 *   node bench/score.mjs           write bench/RESULTS.md
 *   node bench/score.mjs --check   exit 1 if RESULTS.md is out of date (CI)
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { buildPrompt, cost, grade, loadQuestions, BENCH_DIR, CONDITIONS, RECORDED_DIR } from "./lib.mjs";

const { values } = parseArgs({ options: { check: { type: "boolean", default: false } } });
const questions = loadQuestions();

const rows = [];
for (const q of questions) {
  const row = { question: q, byCondition: {} };
  for (const condition of CONDITIONS) {
    const file = join(RECORDED_DIR, condition, `${q.id}.json`);
    if (!existsSync(file)) {
      row.byCondition[condition] = null;
      continue;
    }
    const record = JSON.parse(readFileSync(file, "utf8"));
    const prompt = await buildPrompt(condition, q.fixture, q.question);
    const drifted = createHash("sha256").update(prompt).digest("hex") !== record.promptSha256;
    row.byCondition[condition] = {
      record,
      drifted,
      score: record.answer ? grade(q, record.answer) : { precision: 0, recall: 0, exact: false, unparsed: true },
    };
  }
  rows.push(row);
}

function summarise(condition, subset) {
  const present = subset.map((r) => r.byCondition[condition]).filter((x) => x !== null);
  if (present.length === 0) return null;
  const n = present.length;
  const sum = (f) => present.reduce((s, x) => s + f(x), 0);
  return {
    n,
    exact: sum((x) => (x.score.exact ? 1 : 0)),
    precision: sum((x) => x.score.precision) / n,
    recall: sum((x) => x.score.recall) / n,
    inputTokens: sum((x) => x.record.usage.input_tokens),
    outputTokens: sum((x) => x.record.usage.output_tokens),
    cost: sum((x) => cost(x.record.usage)),
    drifted: sum((x) => (x.drifted ? 1 : 0)),
    unparsed: sum((x) => (x.score.unparsed ? 1 : 0)),
  };
}

const pct = (x) => `${(x * 100).toFixed(0)}%`;
const lines = [];
lines.push("# Benchmark results");
lines.push("");
lines.push("Generated by `node bench/score.mjs` from `bench/recorded/`. Do not edit by hand; re-run the script.");
lines.push("");

const recorded = rows.flatMap((r) => CONDITIONS.map((c) => r.byCondition[c]).filter((x) => x !== null));
if (recorded.length === 0) {
  lines.push("**Not recorded.** No answers exist under `bench/recorded/`. The benchmark has been designed and the");
  lines.push("scorer runs, but no number is claimed until `npm run bench:record` has been run and its output");
  lines.push("committed. See [docs/benchmark.md](../docs/benchmark.md) for what it measures and how to run it.");
  lines.push("");
} else {
  const models = [...new Set(recorded.map((x) => x.record.model))].sort();
  const commits = [...new Set(recorded.map((x) => x.record.commit))].sort();
  const dates = recorded.map((x) => x.record.recordedAt.slice(0, 10)).sort();
  lines.push(`Model: ${models.map((m) => `\`${m}\``).join(", ")}. Recorded ${dates[0]}${dates.at(-1) !== dates[0] ? ` to ${dates.at(-1)}` : ""} at commit ${commits.map((c) => `\`${c.slice(0, 7)}\``).join(", ")}.`);
  lines.push(`${questions.length} questions over 3 fixtures; ${recorded.length} of ${questions.length * CONDITIONS.length} answers recorded.`);
  lines.push("");
  lines.push("## Overall");
  lines.push("");
  lines.push("| Condition | Answered | Exactly right | Precision | Recall | Input tokens | Output tokens | Cost | Prompt drift |");
  lines.push("|---|---|---|---|---|---|---|---|---|");
  for (const condition of CONDITIONS) {
    const s = summarise(condition, rows);
    if (!s) {
      lines.push(`| ${condition} | 0 | - | - | - | - | - | - | - |`);
      continue;
    }
    lines.push(
      `| ${condition} | ${s.n} | ${s.exact} (${pct(s.exact / s.n)}) | ${pct(s.precision)} | ${pct(s.recall)} | ${s.inputTokens.toLocaleString("en-US")} | ${s.outputTokens.toLocaleString("en-US")} | $${s.cost.toFixed(2)} | ${s.drifted}${s.unparsed ? `; ${s.unparsed} unparsed` : ""} |`
    );
  }
  lines.push("");
  lines.push("`raw` = every file of the fixture verbatim. `surface` = the project-surface overview plus a task-scoped context pack. ");
  lines.push("Exactly right = the answer set equals the expected set. Prompt drift = the fixture changed since recording; those rows are stale and should be re-recorded.");
  lines.push("");

  lines.push("## By question kind");
  lines.push("");
  lines.push("| Kind | n | raw exact | raw P / R | surface exact | surface P / R |");
  lines.push("|---|---|---|---|---|---|");
  const kinds = [...new Set(questions.map((q) => q.kind))].sort();
  for (const kind of kinds) {
    const subset = rows.filter((r) => r.question.kind === kind);
    const a = summarise("raw", subset);
    const b = summarise("surface", subset);
    const cell = (s) => (s ? `${s.exact}/${s.n}` : "-");
    const pr = (s) => (s ? `${pct(s.precision)} / ${pct(s.recall)}` : "-");
    lines.push(`| ${kind} | ${subset.length} | ${cell(a)} | ${pr(a)} | ${cell(b)} | ${pr(b)} |`);
  }
  lines.push("");

  lines.push("## By fixture");
  lines.push("");
  lines.push("| Fixture | n | raw exact | surface exact | raw input tokens | surface input tokens |");
  lines.push("|---|---|---|---|---|---|");
  for (const fixture of ["ts-api", "py-api", "go-svc"]) {
    const subset = rows.filter((r) => r.question.fixture === fixture);
    const a = summarise("raw", subset);
    const b = summarise("surface", subset);
    lines.push(`| ${fixture} | ${subset.length} | ${a ? `${a.exact}/${a.n}` : "-"} | ${b ? `${b.exact}/${b.n}` : "-"} | ${a ? a.inputTokens.toLocaleString("en-US") : "-"} | ${b ? b.inputTokens.toLocaleString("en-US") : "-"} |`);
  }
  lines.push("");

  lines.push("## Every question");
  lines.push("");
  lines.push("| Id | Kind | raw | surface | Note |");
  lines.push("|---|---|---|---|---|");
  for (const r of rows) {
    const mark = (x) => {
      if (!x) return "-";
      if (x.score.unparsed) return "unparsed";
      return `${x.score.exact ? "ok" : "miss"} ${pct(x.score.precision)}/${pct(x.score.recall)}${x.drifted ? " (drift)" : ""}`;
    };
    const a = r.byCondition.raw;
    const b = r.byCondition.surface;
    const note = [];
    for (const [name, x] of [["raw", a], ["surface", b]]) {
      if (x && !x.score.exact && x.record.answer) {
        const got = [...(x.record.answer.files ?? []), ...(x.record.answer.commands ?? []), ...(x.record.answer.env ?? [])];
        note.push(`${name} answered: ${got.length ? got.map((g) => `\`${g}\``).join(", ") : "nothing"}`);
      }
    }
    lines.push(`| ${r.question.id} | ${r.question.kind} | ${mark(a)} | ${mark(b)} | ${note.join("; ")} |`);
  }
  lines.push("");
}

const output = `${lines.join("\n")}\n`;
const target = join(BENCH_DIR, "RESULTS.md");
if (values.check) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== output) {
    console.error("bench/RESULTS.md is out of date. Run: node bench/score.mjs");
    process.exit(1);
  }
  console.log("bench/RESULTS.md is current");
} else {
  writeFileSync(target, output);
  console.log(`wrote ${target}`);
}
