/**
 * Agent instructions, generated from evidence.
 *
 * Every repository that works with AI tools grows a hand-written CLAUDE.md or
 * AGENTS.md, and every one of them goes stale without anybody noticing. This
 * renders the same kind of document from the surface instead: commands that
 * were actually run, rules that are actually checked, owners that were
 * declared or derived from real structure. Every line says where it came from.
 *
 * Inferred claims are left out by default. A guess dressed up as an
 * instruction is exactly the failure mode this project exists to prevent.
 *
 * The block is wrapped in markers carrying a fingerprint of its content, so a
 * later scan can tell whether the file still describes the surface it was
 * generated from. That is what makes `AGENTS_MD_STALE` possible.
 */

import { hashContent } from "../model/freshness.js";
import { indexById } from "../model/ids.js";
import type { Capability, Command, Constraint, HealthFinding, Surface } from "../schema/types.js";

export const AGENTS_BEGIN = "<!-- project-surface:begin";
export const AGENTS_END = "<!-- project-surface:end -->";

/** Where a generated block is looked for when checking staleness. */
export const AGENTS_FILES: readonly string[] = Object.freeze(["AGENTS.md", "CLAUDE.md"]);

/** Capabilities listed before the rest is summarised as a count. */
export const DEFAULT_MAX_CAPABILITIES = 40;

export interface AgentsOptions {
  includeInferred?: boolean;
  /** Cap on capabilities listed. The rest is summarised as a count. */
  maxCapabilities?: number;
}

/*
 * Citations name the tier and the proof, never the date: a date would change
 * the fingerprint on every re-verification and make the block look stale when
 * nothing it says has changed. Dates live in the document; `surface why` shows them.
 */
function cite(
  c: Capability | Command | Constraint,
  evidence?: { path?: string; status: string }
): string {
  const tier = c.provenance.tier;
  const freshness = "freshness" in c ? c.freshness?.status : undefined;
  const by = evidence?.path ? ` by ${evidence.path}` : "";
  const name = evidence?.path ?? "the linked evidence";
  const proof = !evidence
    ? ""
    : evidence.status === "passed" && freshness === "fresh"
      ? `, proven${by}`
      : evidence.status === "passed" && freshness === "stale"
        ? `; ${name} passed earlier but the files changed since`
        : evidence.status === "failed"
          ? `; ${name} FAILED`
          : `; ${name} not yet run`;
  if (tier === "declared") return `declared${proof}`;
  if (freshness === "fresh" && evidence?.status === "passed") return `verified${by}`;
  return `${tier}${proof}`;
}

function isTrustworthy(tier: string, includeInferred: boolean): boolean {
  return includeInferred || tier !== "inferred";
}

/**
 * Render the body of the block - everything between the markers, without
 * them. Deterministic for a given surface; no timestamps except the ones the
 * claims themselves carry.
 */
export function renderAgentsBody(surface: Surface, options: AgentsOptions = {}): string {
  const includeInferred = options.includeInferred ?? false;
<<<<<<< HEAD
  const max = options.maxCapabilities ?? DEFAULT_MAX_CAPABILITIES;
  const evidenceById = new Map(surface.evidence.map((e) => [e.id, e]));
=======
  const max = options.maxCapabilities ?? 40;
  const evidenceById = indexById(surface.evidence);
>>>>>>> origin/refactor/core-perf-cleanup
  const lines: string[] = [];

  lines.push(`# ${surface.project.name} - what is known, and how`);
  lines.push("");
  lines.push(
    "Generated by project-surface from `.project/surface.json`. Every line below carries its provenance: " +
      "`declared` means a maintainer wrote it down, `verified` means a command was run and observed, `derived` " +
      "means it was read from real configuration or a parse tree." +
      (includeInferred ? " Lines marked `inferred` are heuristic guesses." : " Heuristic guesses are omitted.")
  );
  lines.push("");

  const commands = surface.commands.filter((c) => isTrustworthy(c.provenance.tier, includeInferred));
  const proven = commands.filter((c) => c.verification?.status === "passed");
  const unproven = commands.filter((c) => c.verification?.status !== "passed");
  lines.push("## Commands");
  lines.push("");
  if (proven.length > 0) {
    lines.push("These have been run and exited successfully:");
    lines.push("");
    for (const c of proven) {
      const where = c.cwd === "." ? "" : ` (in \`${c.cwd}\`)`;
      lines.push(`- \`${c.run}\`${where} - ${c.kind}; ${cite(c, { status: "passed" })}`);
    }
    lines.push("");
  }
  if (unproven.length > 0) {
    lines.push(
      proven.length > 0
        ? "Known from configuration but not yet run here:"
        : "Known from configuration; none has been run here yet:"
    );
    lines.push("");
    for (const c of unproven) {
      const where = c.cwd === "." ? "" : ` (in \`${c.cwd}\`)`;
      const failed = c.verification?.status === "failed" ? " **(last run failed)**" : "";
      lines.push(`- \`${c.run}\`${where} - ${c.kind}; ${c.provenance.tier}${failed}`);
    }
    lines.push("");
  }

  const constraints = surface.constraints.filter(
    (c) => c.status === "active" && isTrustworthy(c.provenance.tier, includeInferred)
  );
  if (constraints.length > 0) {
    lines.push("## Rules");
    lines.push("");
    for (const c of constraints) {
      const status = !c.check
        ? "not machine-checked"
        : c.checked?.status === "violated"
          ? `**currently violated in ${c.checked.violations} place(s)** - see \`surface doctor\``
          : c.checked?.status === "passed"
            ? `machine-checked (${c.check.kind}), passing`
            : `machine-checked (${c.check.kind}), could not be evaluated in the last scan`;
      lines.push(`- ${c.rule}${c.rationale ? ` ${c.rationale}` : ""} _(${c.severity}; ${c.provenance.tier}; ${status})_`);
    }
    lines.push("");
  }

  const risks = surface.risks;
  if (risks.length > 0) {
    lines.push("## Paths that need care");
    lines.push("");
    for (const r of risks) {
      lines.push(`- \`${r.paths.join("`, `")}\` - ${r.type}, approval ${r.approval}: ${r.reason}`);
    }
    lines.push("");
  }

  const capabilities = surface.capabilities
    .filter((c) => isTrustworthy(c.provenance.tier, includeInferred))
    .slice()
    .sort((a, b) => b.confidence - a.confidence || a.id.localeCompare(b.id));
  const omittedInferred = surface.capabilities.length - capabilities.length;
  if (capabilities.length > 0) {
    lines.push("## Where things live");
    lines.push("");
    for (const c of capabilities.slice(0, max)) {
      const owners = c.owners.map((o) => `\`${o.path}\``).join(", ");
      const contract = c.contracts[0] ? `; contract \`${c.contracts[0].path}\`` : "";
      /* Cite the strongest evidence: a passed run beats an unrun link. */
      const linked = c.evidence.map((ref) => evidenceById.get(ref.id)).filter((e) => e !== undefined);
      const evidence = linked.find((e) => e.status === "passed") ?? linked.find((e) => e.status === "failed") ?? linked[0];
      lines.push(`- **${c.id}** - ${c.title}: ${owners}${contract} _(${cite(c, evidence)})_`);
    }
    if (capabilities.length > max) lines.push(`- ...and ${capabilities.length - max} more; run \`surface map\`.`);
    if (omittedInferred > 0) {
      lines.push(`- ${omittedInferred} inferred capabilit${omittedInferred === 1 ? "y is" : "ies are"} not listed; run \`surface inspect\` to see guesses.`);
    }
    lines.push("");
  }

  const env = surface.environment.filter((e) => isTrustworthy(e.provenance.tier, includeInferred));
  if (env.length > 0) {
    lines.push("## Environment");
    lines.push("");
    lines.push(
      "Names only; values are never recorded. " +
        env.map((e) => `\`${e.name}\`${e.required ? "" : " (optional)"}${e.secret ? " (secret)" : ""}`).join(", ") +
        "."
    );
    lines.push("");
  }

  lines.push("## Before you change something");
  lines.push("");
  lines.push("- `surface impact <paths>` says which capabilities and tests a change touches.");
  lines.push("- `surface doctor` lists claims that went stale and rules that are violated.");
  lines.push("- `surface why <id>` shows where any statement above came from.");

  return lines.join("\n");
}

export function agentsFingerprint(body: string): string {
  return hashContent(body).slice(0, 16);
}

/** The full block, markers included. */
export function renderAgentsBlock(surface: Surface, options: AgentsOptions = {}): string {
  const body = renderAgentsBody(surface, options);
  /* Every option that changes the body is recorded in the marker, so the
     staleness check re-renders with the same options and compares like with
     like. A block written with --max-capabilities 5 is not stale because the
     default would have listed 40. */
  const flags =
    (options.includeInferred ? " inferred=1" : "") +
    (options.maxCapabilities !== undefined && options.maxCapabilities !== DEFAULT_MAX_CAPABILITIES
      ? ` max=${options.maxCapabilities}`
      : "");
  return `${AGENTS_BEGIN} fingerprint=${agentsFingerprint(body)}${flags} -->\n${body}\n${AGENTS_END}`;
}

export interface AgentsMarker {
  fingerprint: string;
  includeInferred: boolean;
  maxCapabilities: number;
  start: number;
  end: number;
}

/** Find an existing generated block in a file's content. */
export function findAgentsBlock(content: string): AgentsMarker | null {
  const start = content.indexOf(AGENTS_BEGIN);
  if (start < 0) return null;
  const headerEnd = content.indexOf("-->", start);
  const end = content.indexOf(AGENTS_END, start);
  if (headerEnd < 0 || end < 0) return null;
  const header = content.slice(start, headerEnd);
  const fingerprint = /fingerprint=([0-9a-f]+)/.exec(header)?.[1] ?? "";
  const max = /\bmax=(\d+)\b/.exec(header)?.[1];
  return {
    fingerprint,
    includeInferred: /\binferred=1\b/.test(header),
    maxCapabilities: max ? Number(max) : DEFAULT_MAX_CAPABILITIES,
    start,
    end: end + AGENTS_END.length,
  };
}

/**
 * Compare each committed block against what the current surface would render
 * with the options recorded in its marker. One finding per file that no
 * longer describes the surface; a file without a block is not a finding.
 */
export function detectAgentsDrift(
  files: ReadonlySet<string>,
  readFile: (relPath: string) => string | null,
  surface: Surface
): HealthFinding[] {
  const findings: HealthFinding[] = [];
  for (const path of AGENTS_FILES) {
    if (!files.has(path)) continue;
    const content = readFile(path);
    if (content === null) continue;
    const block = findAgentsBlock(content);
    if (!block) continue;
    const expected = agentsFingerprint(
      renderAgentsBody(surface, { includeInferred: block.includeInferred, maxCapabilities: block.maxCapabilities })
    );
    if (expected === block.fingerprint) continue;
    findings.push({
      code: "AGENTS_MD_STALE",
      severity: "warn",
      message: `${path} contains a generated project-surface block that no longer matches the surface: what it tells an agent is out of date.`,
      subject: { kind: "project", id: path },
      paths: [path],
      remediation: `Run: surface agents --write ${path}`,
    });
  }
  return findings;
}

/**
 * Insert or replace the generated block. Anything a human wrote outside the
 * markers is preserved byte for byte; a file without markers gets the block
 * appended after a blank line.
 */
export function upsertAgentsBlock(existing: string | null, block: string): string {
  if (existing === null || existing.trim() === "") return `${block}\n`;
  const found = findAgentsBlock(existing);
  if (!found) {
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    return `${existing}${sep}${block}\n`;
  }
  return `${existing.slice(0, found.start)}${block}${existing.slice(found.end)}`;
}
